language: ruby
rvm:
- 2.3.3
env:
  global:
    secure: yQDLk7BO4vFBcVDP6sR7YBvDlR5ZLc/hnDww4FGOma8KtdmZqcKHi0om+QE5i1msVVY3oYSQaaE5PGzaOCDnxFks7ybyYqVvhaskBwzG3Y8PhSWaKqWzxgYvEI0wGr6aPp/Z83bP01D1p5MMaKzzOju5I/M0qKb5G8ZP/y3eNzrWyFf+hvGs6M/RpcNU8o1stOsJJ/RhUTLqRgBgUCddbD3c8QC9g/DtxbwcGIXVNfClDG2cYxPy+qebWq3ucWYpB2KIRvFeLa+NOgXtW2DuF/zFMCIo0Ge19VOXGslJm4u9xwZYCG9PzVjaFDrf8xGZSo2gvzi8IZe7My03LzafzGyV6QKo+anOLbm9E2guiLJpBKHz40PhzdSpDl1pus/fjG0OzpmJhEckfsn52rhE6ijYkK77kAzHFkp/RfJOU/x4ImoouwLLZCsy7U6T/bq4XI5GNs/wPCDttw5+VZup1QMjMtqhPTUEaNoHcI9AF65LuQIB/InIWgFqZkL5xVQ9T21C+jNIcTnhmgYKaH+EF9sovcZtyAGcnM4eyuDPyDZHYcnvVED338+JPkrazMmdTyR5BAZHgAIXNRbVwy616UNKXKN9m3eKKCCEtw87SOaWN7q9Qx82ow7FtnVq9T1v3xCgxd8BP7wtFIAKcg3Wac/cZwRFP729Y+wsT5BrYQQ=
